image: node:8.7

before_script:
  - npm install
  - npm install -g firebase-tools

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  only:
    - master
  script:
    - run-s deploy:setup && firebase deploy --token "${FIREBASE_TOKEN}"
