image: node:8.7

before_script:
  - yarn global add node-gyp
  - yarn global add firebase-tools
  - yarn

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  only:
    - master
  script:
    - run-s deploy:setup && firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token ${FIREBASE_TOKEN}
